### ISSUE TITLE
Unterstützung von 2FA via TOTP

### ISSUE THREAD

**Issue by daniel-lerch** [canchanchara/keycloak-churchtools-storage-provider#1]
Eine der zentralen Limitierungen von ChurchTools LDAP Wrappern wie [milux/ctldap](https://github.com/milux/ctldap) ist, dass keine Zwei-Faktor-Authentifizierung unterstützt wird. Durch ein Keycloak Plugin könnte es möglich sein, diesen zusätzlichen Schritt zu unterstützen.

**Comment by canchanchara** [comment]
Church Tools plant die Funktionalität glaube ich selbst bald bereitzustellen. Siehe https://forum.church.tools/topic/2814/authentifizierung-mittels-oauth2/24?_=1696226454204

Ich bin selber etwas unschlüssig, ob ich dieses Projekt hier weitertreibe oder auf Church Tools warte.
Leider weiß man nicht, wann Church Tools es selbst haben wird und sich eine eigene Lösung noch lohnt.

Hab das Feature aber auf dem Schirm, wenn ich es selber weitertreiben sollte.

**Comment by canchanchara** [comment]
@daniel-lerch 
hat mich dann doch etwas beschäftigt heute. Mit https://github.com/canchanchara/keycloak-churchtools-totp-provider kann man dann auch TOTP von Church Tools nutzen.

**Comment by daniel-lerch** [comment]
# 🤯 
@canchanchara du bist verrückt. Ich bin noch nicht mal dazu gekommen, meine zuerst selbst gebaute JAR zu testen, da hast du Feature Requests implementiert, über die Leute in Foren seit Jahren nachdenken, aber noch nie jemand umgesetzt hat 😂
