### ISSUE TITLE
Keycloak setup guide with Docker

### ISSUE THREAD

**Issue by daniel-lerch** [canchanchara/keycloak-churchtools-storage-provider#12]
Keycloak ist nicht ganz einfach zu installieren. Schon das richtige Docker Image auszuwählen erfordert einige Recherche und dann gibt es sehr viele Konfigurationsmöglichkeiten.

Im Rahmen dieses Plugins würde ich jetzt ungern alle Optionen des offiziellen Keycloak Images erklären, aber vielleicht die offizielle Dokumentation verlinken, eine Anleitung zum Setup verlinken und eine `docker-compose.yml` Datei für ein konkretes Setup mit Datenbank und Reverse-Proxy zur Verfügung stellen.

@fschrempf wäre das für dich ausreichend, um Keycloak in akzeptabler Zeit zum Laufen zu bekommen?

**Comment by fschrempf** [comment]
> @fschrempf wäre das für dich ausreichend, um Keycloak in akzeptabler Zeit zum Laufen zu bekommen?

Ja, dein docker-compose Beispiel hat ja schon geholfen. Ganz unerfahren bin ich tatsächlich auch nicht. Ich hatte Keycloak schon mal in Docker produktiv über einen längeren Zeitraum am laufen (ohne CT). Nur als ich es jetzt neu aufgesetzt habe bin ich eben auf das in https://github.com/canchanchara/keycloak-churchtools-storage-provider/issues/11 beschriebene Problem gestoßen.

Laut KC Doku soll man ja ein eigenes Image bauen und das wollte ich im ersten Schritt vermeiden, weshalb ich das Bitnami-Image probiert habe. Deine Lösung gefällt mir da aber schon besser und sie funktioniert!
