### ISSUE TITLE
Add `picture` claim to profile scope

### ISSUE THREAD

**Issue by daniel-lerch** [canchanchara/keycloak-churchtools-storage-provider#13]
OpenID Connect unterstützt die Angabe einer URL zum Profilbild ([Spezifikation](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims)). ChurchTools bietet in der API `/api/persons/{ID}` eine `imageUrl` an, die eine öffentliche URL zum Profilbild des Nutzers enthält. Diese URL könnte vom ChurchTools Provider einfach weitergereicht werden.

**Comment by canchanchara** [comment]
Finde ich super, gerne ein PR dafür erstellen, habe die Tage wenig Zeit dafür
