### ISSUE TITLE
Update to Keycloak 24

### ISSUE THREAD

**Issue by daniel-lerch** [canchanchara/keycloak-churchtools-storage-provider#14]
This ChurchTools Storage Provider was developed for Keycloak 22 which has not been supported for 6 months. Instead we should support the latest and only supported version Keycloak 24.

**Comment by canchanchara** [comment]
Ich habe diese Tage/Wochen wenig Priorität, das zu aktualisieren. Ein Pull Request von dir würde ich aber reinmergen.
