### ISSUE TITLE
Kompilierte JAR-Archive zum Download

### ISSUE THREAD

**Issue by daniel-lerch** [canchanchara/keycloak-churchtools-storage-provider#2]
Die Installation dieses Storage Providers könnte man Nutzern deutlich vereinfachen, indem man über GitHub Releases kompilierte JAR-Archive zur Verfügung stellen würde. Da es sich aktuell noch um einen Prototypen handelt, könnte der Download entsprechend als Preview Release kenntlich gemacht werden.

**Comment by canchanchara** [comment]
Hab eins erzeugt mit dem aktuellen Code Stand.
Ist aber nachwievor ein Prototyp und nicht direkt für Produktion empfohlen.

https://github.com/canchanchara/keycloak-churchtools-storage-provider/releases/tag/0.0.1-alpha
