### ISSUE TITLE
Standard claims zum user info Endpunkt hinzufügen

### ISSUE THREAD

**Issue by daniel-lerch** [canchanchara/keycloak-churchtools-storage-provider#3]
Mit keycloak-churchtools-storage-provider gibt der user info Endpunkt aktuell nur drei Claims zurück:
```json
{
  "sub": "f:37c73a75-123a-4c79-8402-d0510febb5a8",
  "email_verified": false,
  "preferred_username": "admin"
}
```

OpenID Connect sieht jedoch noch viele weitere Claims vor: [Dokumentation](https://openid.net/specs/openid-connect-basic-1_0.html#StandardClaims). 

Zum Vergleich der user info Endpunkt wenn man LDAP Federation mit [fschrempf/ctldap](https://github.com/fschrempf/ctldap) benutzt und ein paar Mapper korrekt konfiguriert hat:

```json
{
  "sub": "0875d65b-c05c-454d-b286-0d15ab374fd4",
  "email_verified": false,
  "name": "Max Mustermann",
  "preferred_username": "admin",
  "given_name": "Max",
  "family_name": "Mustermann",
  "email": "max.mustermann@example.org"
}
```

Ich denke zumindest die Claims wie bei der LDAP Federation sollten unterstützt werden, damit andere Apps damit korrekt arbeiten.

**Comment by canchanchara** [comment]
Hab ein 0.0.2-alpha veröffentlich, kannst du es damit probieren?
E-Mail Vorname und NAchname sollten jetzt auch mitkommen.

**Comment by daniel-lerch** [comment]
Claims werden mit `0.0.2-alpha` jetzt korrekt übertragen 👍🏼
