### ISSUE TITLE
API Authentifizierung mit Login Token

### ISSUE THREAD

**Issue by daniel-lerch** [canchanchara/keycloak-churchtools-storage-provider#5]
Dieses Feature ist zur reinen Funktion nicht nötig, könnte aber den Login spürbar schneller machen. Bisher wird für jeden API Call zuerst über den Login Endpunkt eine Session erzeugt. Stattdessen könnte man aber auch direkt ein zeitlich unbegrenzt gültiges Login Token in der Konfiguration setzen und sich den Login komplett sparen. Siehe [Dokumentation zur API Authentifizierung](https://hilfe.church.tools/wiki/0/API%20Authentifizierung).

@canchanchara falls du das nicht selbst implementieren möchtest, kannst du das gerne sagen oder ein _help wanted_ Label hinzufügen. Dann stelle ich in den nächsten Tagen einen Pull Request dazu.

**Comment by canchanchara** [comment]
@daniel-lerch du kannst da gerne ein Pull Request stellen.
Mir ist aktuell kein System bekannt, wie ich die Session in keycloak hübsch speichern kann.
Man hat da nur Standard Java Möglichkeiten zur Verfügung.
