### ISSUE TITLE
Schnittstellen strikt read-only implementieren

### ISSUE THREAD

**Issue by daniel-lerch** [canchanchara/keycloak-churchtools-storage-provider#6]
Keycloak ermöglicht eine bidirektionale Synchronisation mit externen User Storages. Im Fall von ChurchTools soll diese jedoch ausschließlich lesend erfolgen und auch keine Informationen im Cache von Keycloak verändert werden können. Wahrscheinlich lassen sich Modifikationen wie Vorname ändern auch durch eine entsprechende Konfiguration von Keycloak verhindern. Ich finde es allerdings sauberer, das direkt im Code umzusetzen, sodass man bei der Konfiguration nichts mehr falsch machen kann.

@canchanchara ich habe dazu bereits etwas in einem Fork implementiert, würde den Code noch mit deinen Änderungen von heute Morgen zusammenführen und dann einen Pull Request erstellen.

**Comment by canchanchara** [comment]
das wäre ein gutes Feature, gerne ein Pullrequest dafür erstellen.
